# Generated by Django 3.1.6 on 2021-02-05 06:50

from django.db import migrations, models
import mzakapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mzakapp', '0002_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[mzakapp.validators.validate_email]),
        ),
    ]
