# Generated by Django 3.1.6 on 2021-02-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzakapp', '0006_customerreportrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='first_name', max_length=30),
        ),
    ]
